language: python
python:
  - "2.7"
  - "3.4"

# command to install dependancies

install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage

env:
  - DB=postgres

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE navyget_api" -U postgres
  - psql -c "CREATE DATABASE test_navy_db" -U postgres

# command to run tests
script: nosetests --with-coverage --cover-package=app

after_success:
  - coveralls