language: python
python:
  - "3.6"

# command to install dependancies

install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage

env:
  - DB=mongodb

services:
  - mongodb

# command to run tests
script: nosetests --with-coverage --cover-package=app

after_success:
  - coveralls